# settings.yaml - Chatbot project settings

model:
  name: "DialoGPT-small"
  path: "models/dialoGPT-small"
  max_length: 1000
  pad_token_id: 50256
  do_sample: true
  top_k: 50
  top_p: 0.95

gui:
  title: "AI Chatbot"
  width: 600
  height: 500

logging:
  log_dir: "logs"
  chatbot_log: "chatbot.log"
  error_log: "errors.log"
